#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = ti.targets.arm.elf.M4{1,0,18.12,4
#
water_monitor.xem4: package/cfg/water_monitor.xem4.mak

clean::
	-$(RM) package/cfg/water_monitor.xem4.mak
